FROM gradle:8.10-jdk22 AS build
WORKDIR /app
COPY . .
RUN gradle build -x test

FROM eclipse-temurin:22-jre
WORKDIR /app
COPY --from=build /app/build/libs/devotion-backend-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
